# Generated by Django 5.0.1 on 2024-03-30 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('dept', models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('eee', 'EEE'), ('ece', 'ECE'), ('cse', 'CSE'), ('ai_ds', 'AI&DS'), ('ds', 'DS'), ('crt', 'CRT'), ('hns', 'H&S')], max_length=20)),
                ('sem', models.CharField(choices=[('1-1', 'I-I'), ('1-2', 'I-II'), ('2-1', 'II-I'), ('2-2', 'II-II'), ('3-1', 'III-I'), ('3-2', 'III-II'), ('4-1', 'IV-I'), ('4-2', 'IV-II')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('co', 'CO'), ('ns', 'NS')], default='ns', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('eee', 'EEE'), ('ece', 'ECE'), ('cse', 'CSE'), ('ai_ds', 'AI&DS'), ('ds', 'DS'), ('crt', 'CRT'), ('hns', 'H&S')], max_length=20)),
                ('sem', models.CharField(choices=[('1-1', 'I-I'), ('1-2', 'I-II'), ('2-1', 'II-I'), ('2-2', 'II-II'), ('3-1', 'III-I'), ('3-2', 'III-II'), ('4-1', 'IV-I'), ('4-2', 'IV-II')], max_length=20)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('topic_ids', models.ManyToManyField(related_name='courses', to='users.topic')),
            ],
        ),
    ]
