# Generated by Django 5.0.1 on 2024-02-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('dept', models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('eee', 'EEE'), ('ece', 'ECE'), ('cse', 'CSE'), ('ai_ds', 'AI&DS'), ('ds', 'DS'), ('crt', 'CRT'), ('hns', 'H&S')], max_length=20)),
                ('sem', models.CharField(choices=[('1-1', 'I-I'), ('1-2', 'I-II'), ('2-1', 'II-I'), ('2-2', 'II-II'), ('3-1', 'III-I'), ('3-2', 'III-II'), ('4-1', 'IV-I'), ('4-2', 'IV-II')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('co', 'CO'), ('ns', 'NS')], default='ns', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('dept', models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('eee', 'EEE'), ('ece', 'ECE'), ('cse', 'CSE'), ('ai_ds', 'AI&DS'), ('ds', 'DS'), ('crt', 'CRT'), ('hns', 'H&S')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('eee', 'EEE'), ('ece', 'ECE'), ('cse', 'CSE'), ('ai_ds', 'AI&DS'), ('ds', 'DS'), ('crt', 'CRT'), ('hns', 'H&S')], max_length=20)),
                ('sem', models.CharField(choices=[('1-1', 'I-I'), ('1-2', 'I-II'), ('2-1', 'II-I'), ('2-2', 'II-II'), ('3-1', 'III-I'), ('3-2', 'III-II'), ('4-1', 'IV-I'), ('4-2', 'IV-II')], max_length=20)),
                ('topic_ids', models.ManyToManyField(related_name='courses', to='report.topic')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='report.usermodel')),
            ],
        ),
    ]
