# Generated by Django 5.0.1 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='uname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
