# Generated by Django 5.0.1 on 2024-02-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_usermodel_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='report.usermodel'),
        ),
    ]
