# Generated by Django 5.0.1 on 2024-02-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_lessonplan_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='faculty',
            field=models.ForeignKey(default='hii', on_delete=django.db.models.deletion.CASCADE, to='report.usermodel'),
            preserve_default=False,
        ),
    ]
