# Generated by Django 5.0.1 on 2024-02-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_lessonplan_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='report.usermodel'),
        ),
    ]
