# Generated by Django 5.0.1 on 2024-02-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_lessonplan_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.usermodel'),
        ),
    ]
